#!/usr/bin/python
import time
import wakeonlan
import discord
from dotenv import load_dotenv

load_dotenv()
TOKEN = "TOKEN"
time.sleep(10)
intents = discord.Intents.default()
client = discord.Client(intents=intents)

@client.event
async def on_ready():
    print(f'{client.user} has connected to Discord!')

@client.event
async def on_message(message):
    if message.channel.name == "channelName":
        wakeonlan.send_magic_packet("MAC_ADDR", interface="IP_PI")
        print("send")

client.run(TOKEN)
